# env vars
LOAD_DB_DATA: 0
RESTAURANT_DATA_URL: https://gist.githubusercontent.com/seahyc/b9ebbe264f8633a1bf167cc6a90d4b57/raw/021d2e0d2c56217bad524119d1c31419b2938505/restaurant_with_menu.json
USER_DATA_URL: https://gist.githubusercontent.com/seahyc/de33162db680c3d595e955752178d57d/raw/785007bc91c543f847b87d705499e86e16961379/users_with_purchase_history.json

DB_URL: 127.0.0.1:3306
DB_USERNAME: root
DB_PASSWORD: root

logging:
  file:
    name: ./log/fd.log
  level.idv: DEBUG

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

server:
  compression:
    enabled: true
    min-response-size: 1024
  http2:
    enabled: true

spring:
  application.name: food-delivery
  main:
    banner-mode: 'off'
  datasource:
    url: jdbc:mysql://${DB_URL}/demo?characterEncoding=utf-8&allowMultiQueries=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: false
  jackson:
    default-property-inclusion: non_null

springdoc:
  api-docs:
    path: /api-docs